BEGIN;
DROP DATABASE IF EXISTS Progetto;
CREATE DATABASE Progetto;
COMMIT;

USE Progetto;

DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT (
    Username VARCHAR(30) PRIMARY KEY,
    DomSic VARCHAR(50) NOT NULL,
    RispSic VARCHAR(30) NOT NULL,
    Password VARCHAR(30) NOT NULL,
    Credito NUMERIC(8,2) DEFAULT(0) NOT NULL,
    Utente CHAR(16) NOT NULL REFERENCES UTENTE(CodFiscale) ON DELETE CASCADE ON UPDATE CASCADE,
    CHECK(Credito>=0)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS PRODOTTO;
CREATE TABLE PRODOTTO (
    Modello VARCHAR(10),
    Marca VARCHAR(20),
    Soglia SMALLINT NOT NULL,
    Facce TINYINT NOT NULL,
    Prezzo NUMERIC(8,2) NOT NULL,
    NomeProd VARCHAR(30),
    Descrizione VARCHAR(100) NOT NULL,
    ModelloOriginale VARCHAR(10),
    MarcaOriginale VARCHAR(20),
    PRIMARY KEY(Modello,Marca),
    FOREIGN KEY(ModelloOriginale, MarcaOriginale) REFERENCES PRODOTTO(Modello,Marca) ON DELETE CASCADE ON UPDATE CASCADE,
    CHECK(Soglia > 0 AND Prezzo > 0 AND Facce > 0)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS ACQUISTO;
CREATE TABLE ACQUISTO (
    Account VARCHAR(30) REFERENCES ACCOUNT(Username) ON DELETE CASCADE ON UPDATE CASCADE,
    ModelloProd VARCHAR(10),
    MarcaProd VARCHAR(20),
    PRIMARY KEY(Account, ModelloProd, MarcaProd),
    FOREIGN KEY(ModelloProd,MarcaProd) REFERENCES PRODOTTO(Modello,Marca) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS APPLICAZIONE;
CREATE TABLE APPLICAZIONE (
    ModelloProd VARCHAR(10),
    MarcaProd VARCHAR(20),
    EstGaranzia INT REFERENCES ESTENSIONE_GARANZIA(CodEstensione) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(ModelloProd, MarcaProd, EstGaranzia),
    FOREIGN KEY(ModelloProd,MarcaProd) REFERENCES PRODOTTO(Modello,Marca) ON DELETE NO ACTION ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS AREA_GEOGRAFICA;
CREATE TABLE AREA_GEOGRAFICA (
    CodArea INT PRIMARY KEY AUTO_INCREMENT,
    CentroRip INT /*NOT NULL*/ REFERENCES CENTRO_RIPARAZIONE(CodCentro) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS ASSISTENZA;
CREATE TABLE ASSISTENZA (
    Ticket INT PRIMARY KEY AUTO_INCREMENT,
    Sistemato BOOLEAN DEFAULT(NULL),
    Data DATE NOT NULL DEFAULT(CURRENT_DATE),
    Tipologia VARCHAR(8) NOT NULL,
    Unita INT NOT NULL REFERENCES UNITA(CodSer) ON DELETE NO ACTION ON UPDATE NO ACTION,
    Casistica INT REFERENCES CASISTICA(CodCasistica) ON DELETE SET NULL ON UPDATE CASCADE,
    CodiceErrore INT REFERENCES CODICE_ERRORE(CodErrore) ON DELETE SET NULL ON UPDATE CASCADE,
	CHECK(Tipologia='Virtuale' OR Tipologia='Fisica')
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS AUTODIAGNOSI;
CREATE TABLE AUTODIAGNOSI (
    CodDiagnoasi INT PRIMARY KEY AUTO_INCREMENT,
    Testo VARCHAR(50) NOT NULL,
    Ordine TINYINT NOT NULL,
    Casistica INT NOT NULL REFERENCES CASISTICA(CodCasistica) ON DELETE CASCADE ON UPDATE CASCADE,
    NextSi INT REFERENCES AUTODIAGNOSI(CodDiagnosi) ON DELETE SET NULL ON UPDATE CASCADE,
    NextNo INT REFERENCES AUTODIAGNOSI(CodDiagnosi) ON DELETE SET NULL ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS CAMPIONE;
CREATE TABLE CAMPIONE (
    Operaio INT REFERENCES OPERAIO(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    OperazioneSig INT REFERENCES OPERAZIONE_SIGNIFICATIVA(CodiceOpSig) ON DELETE CASCADE ON UPDATE CASCADE,
    TempoMed SMALLINT NOT NULL,
    TempoMax SMALLINT NOT NULL,
    TempoMin SMALLINT NOT NULL,
    PRIMARY KEY(Operaio, OperazioneSig),
    CHECK(TempoMed>0 AND TempoMax>0 AND TempoMin>0)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS CARATTERISTICA;
CREATE TABLE CARATTERISTICA (
    CodCaratteristica INT,
    ElemGiunzione INT REFERENCES ELEMENTO_GIUNZIONE(CodGiunzione) ON DELETE CASCADE ON UPDATE CASCADE,
    Descrizione VARCHAR(50) NOT NULL,
    Valore NUMERIC(5,2) NOT NULL,
    UDM VARCHAR(10) NOT NULL,
    PRIMARY KEY(CodCaratteristica, ElemGiunzione),
    CHECK(Valore>0)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS CASISTICA;
CREATE TABLE CASISTICA (
    CodCasistica INT PRIMARY KEY AUTO_INCREMENT,
    Testo VARCHAR(50) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS INDIRIZZO;
CREATE TABLE INDIRIZZO (
    Via VARCHAR(50),
    NumCivico VARCHAR(4),
    Citta VARCHAR(50),
    CAP NUMERIC(5) NOT NULL REFERENCES CODICE_POSTALE(CAP) ON DELETE NO ACTION ON UPDATE CASCADE,
    PRIMARY KEY(Via, NumCivico, Citta)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS CENTRO_RIPARAZIONE;
CREATE TABLE CENTRO_RIPARAZIONE (
    CodCentro INT PRIMARY KEY AUTO_INCREMENT,
    Via VARCHAR(50) NOT NULL,
    NumCivico VARCHAR(4) NOT NULL,
    Citta VARCHAR(50) NOT NULL,
    FOREIGN KEY(Via, NumCivico, Citta) REFERENCES INDIRIZZO(Via, NumCivico, Citta) ON DELETE NO ACTION ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS CODICE_ERRORE;
CREATE TABLE CODICE_ERRORE (
    CodErrore INT PRIMARY KEY AUTO_INCREMENT,
    ModelloProd VARCHAR(10) NOT NULL,
    MarcaProd VARCHAR(20) NOT NULL,
    Guasto INT NOT NULL REFERENCES GUASTO(CodGuasto) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(ModelloProd,MarcaProd) REFERENCES PRODOTTO(Modello,Marca) ON DELETE NO ACTION ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS CODICE_POSTALE;
CREATE TABLE CODICE_POSTALE (
    CAP NUMERIC(5) PRIMARY KEY,
    AreaGeografica INT NOT NULL REFERENCES AREA_GEOGRAFICA(CodArea) ON DELETE NO ACTION ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS COINVOLGIMENTO;
CREATE TABLE COINVOLGIMENTO (
    Guasto INT REFERENCES GUASTO(CodGuasto) ON DELETE CASCADE ON UPDATE CASCADE,
    Parte INT REFERENCES PARTE(CodParte) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(Guasto, Parte)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS COMPOSIZIONE;
CREATE TABLE COMPOSIZIONE (
    Parte INT REFERENCES PARTE(CodParte) ON DELETE NO ACTION ON UPDATE CASCADE,
    Materiale VARCHAR(20) REFERENCES MATERIALE(NomeMateriale) ON DELETE NO ACTION ON UPDATE CASCADE,
    Quantita INTEGER NOT NULL,
    PRIMARY KEY(Parte, Materiale),
    CHECK(Quantita>0)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS COPERTURA;
CREATE TABLE COPERTURA (
    EstensioneGaranzia INT REFERENCES ESTENSIONE_GARANZIA(CodEstensione) ON DELETE CASCADE ON UPDATE CASCADE,
    Guasto INT REFERENCES GUASTO(CodGuasto) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(EstensioneGaranzia, Guasto)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS DIAGNOSTICA;
CREATE TABLE DIAGNOSTICA (
    Intervento INT REFERENCES INTERVENTO_PREVENTIVO(Ticket) ON DELETE CASCADE ON UPDATE CASCADE,
    Guasto INT REFERENCES GUASTO(CodGuasto) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(Intervento, Guasto)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS DOCUMENTO;
CREATE TABLE DOCUMENTO (
    NumDoc VARCHAR(10) PRIMARY KEY,
    Tipo VARCHAR(20) NOT NULL,
    Scadenza DATE NOT NULL,
    EnteRilascio VARCHAR(50) NOT NULL,
    CHECK(Tipo = 'Carta di identita' OR Tipo = 'Patente' OR Tipo = 'Passaporto')
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS ELEMENTO_GIUNZIONE;
CREATE TABLE ELEMENTO_GIUNZIONE (
    CodGiunzione INT PRIMARY KEY AUTO_INCREMENT,
    Tipo VARCHAR(30) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS SUCCESSIONE;
CREATE TABLE SUCCESSIONE (
    Operazione INT REFERENCES OPERAZIONE(CodiceOp) ON DELETE CASCADE ON UPDATE CASCADE,
    Ordine TINYINT,
    Sequenza INT REFERENCES SEQUENZA(CodSequenza) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(Operazione, Ordine, Sequenza),
    CHECK(Ordine > 0)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS STAZIONE;
CREATE TABLE STAZIONE (
    NumStazione SMALLINT,
    Linea INT REFERENCES LINEA_PRODUZIONE(CodLinea) ON DELETE CASCADE ON UPDATE CASCADE,
    Operaio INT NOT NULL REFERENCES OPERAIO(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
    PRIMARY KEY(NumStazione,Linea),
    CHECK(NumStazione > 0)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS ESECUZIONE;
CREATE TABLE ESECUZIONE (
    Operazione INT,
    Ordine TINYINT,
    Sequenza INT,
    Stazione SMALLINT,
    Linea INT,
    PRIMARY KEY(Operazione, Ordine, Sequenza, Stazione, Linea),
    FOREIGN KEY(Operazione, Ordine, Sequenza) REFERENCES SUCCESSIONE(Operazione, Ordine, Sequenza) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(Stazione, Linea) REFERENCES STAZIONE(NumStazione, Linea) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS ESTENSIONE_GARANZIA;
CREATE TABLE ESTENSIONE_GARANZIA (
    CodEstensione INT PRIMARY KEY AUTO_INCREMENT,
    Costo NUMERIC(7,2) NOT NULL,
    Mesi TINYINT DEFAULT(12) NOT NULL,
    CHECK(Costo>0 AND Mesi>0)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS FISSAGGIO;
CREATE TABLE FISSAGGIO (
    Operazione INT REFERENCES OPERAZIONE(CodiceOp) ON DELETE CASCADE ON UPDATE CASCADE,
    Giunzione INT REFERENCES ELEMENTO_GIUNZIONE(CodGiunzione) ON DELETE NO ACTION ON UPDATE CASCADE,
    PRIMARY KEY(Operazione, Giunzione)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS GUASTO;
CREATE TABLE GUASTO (
    CodGuasto INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(20) NOT NULL,
    Descrizione VARCHAR(50) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS HUB;
CREATE TABLE HUB (
    CodiceHub INT PRIMARY KEY AUTO_INCREMENT,
    Via VARCHAR(50) NOT NULL,
    NumCivico VARCHAR(4) NOT NULL,
    Citta VARCHAR(50) NOT NULL,
    FOREIGN KEY(Via, NumCivico, Citta) REFERENCES INDIRIZZO(Via, NumCivico, Citta) ON DELETE NO ACTION ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS INCREMENTO;
CREATE TABLE INCREMENTO (
    Unita INT REFERENCES UNITA(CodSer) ON DELETE CASCADE ON UPDATE CASCADE,
    EstGaranzia INT REFERENCES ESTENSIONE_GARANZIA(CodEstensione)ON DELETE CASCADE ON UPDATE CASCADE, /*AVEVAMO SBAGLIATO*/
    DataInizio DATE DEFAULT(CURRENT_DATE),
    PRIMARY KEY(Unita, EstGaranzia, DataInizio)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS INTERVENTO_PREVENTIVO;
CREATE TABLE INTERVENTO_PREVENTIVO (
    Ticket INT PRIMARY KEY AUTO_INCREMENT REFERENCES ASSISTENZA(Ticket) ON DELETE NO ACTION ON UPDATE CASCADE,
    Accettato BOOLEAN DEFAULT(NULL),
    Preventivo INTEGER DEFAULT(NULL),
    DataPrev DATE NOT NULL,
    OrarioPrev TIME NOT NULL,
    Tecnico INT DEFAULT(NULL) REFERENCES TECNICO(Matricola) ON DELETE SET NULL ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS INTERVENTO_RIPARATIVO;
CREATE TABLE INTERVENTO_RIPARATIVO (
    Ticket INT PRIMARY KEY AUTO_INCREMENT REFERENCES INTERVENTO_PREVENTIVO(Ticket) ON DELETE CASCADE ON UPDATE CASCADE,
    DataRip DATE NOT NULL,
    OrarioRip TIME NOT NULL,
    Tecnico INT REFERENCES TECNICO(Matricola) ON DELETE SET NULL ON UPDATE CASCADE,
    CentroRip INT REFERENCES CENTRO_RIPARAZIONE(CodCentro) ON DELETE SET NULL ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS LINEA_PRODUZIONE;
CREATE TABLE LINEA_PRODUZIONE (
    CodLinea INT PRIMARY KEY AUTO_INCREMENT,
    Sede VARCHAR(50) NOT NULL,
    T SMALLINT NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS LOG;
CREATE TABLE LOG (
    UnitaResa INT REFERENCES UNITA_RESA(Unita) ON DELETE NO ACTION ON UPDATE CASCADE,
    Test INT REFERENCES TEST(CodiceTest) ON DELETE CASCADE ON UPDATE CASCADE,
    Parte INT REFERENCES PARTE(CodParte) ON DELETE NO ACTION ON UPDATE CASCADE,
    Successo BOOLEAN NOT NULL,
    PRIMARY KEY(UnitaResa, Test, Parte)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS LOTTO;
CREATE TABLE LOTTO (
    CodiceLotto INT PRIMARY KEY AUTO_INCREMENT,
    DurataPreventivata TINYINT,                /*In ore*/
    DataInizioProd TIMESTAMP DEFAULT(CURRENT_TIMESTAMP) NOT NULL,
    DataFineProd TIMESTAMP DEFAULT(NULL),
    Tipologia VARCHAR(14) NOT NULL DEFAULT('Nuove'),
    Linea INT REFERENCES LINEA_PRODUZIONE(CodLinea) ON DELETE SET NULL ON UPDATE CASCADE,
    Sequenza INT REFERENCES SEQUENZA(CodSequenza) ON DELETE SET NULL ON UPDATE CASCADE,
    CHECK(Tipologia = 'Nuove' OR Tipologia = 'Rese' OR Tipologia = 'Ricondizionate')
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS MAGAZZINO;
CREATE TABLE MAGAZZINO (
    CodMagazzino INT PRIMARY KEY AUTO_INCREMENT,
    Capienza SMALLINT NOT NULL,
    Predisposizione VARCHAR(100) NOT NULL,
    CHECK(Capienza>0)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS MATERIALE;
CREATE TABLE MATERIALE (
    NomeMateriale VARCHAR(20) PRIMARY KEY,
    ValoreAlKg NUMERIC(8,2) NOT NULL,
    CHECK(ValoreAlKg>0)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS MOTIVAZIONE;
CREATE TABLE MOTIVAZIONE (
    CodMotivazione INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(20) NOT NULL UNIQUE,
    Descrizione VARCHAR(50) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS OPERAIO;
CREATE TABLE OPERAIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(20) NOT NULL,
    Cognome VARCHAR(30) NOT NULL,
    DataNascita DATE NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS OPERAZIONE;
CREATE TABLE OPERAZIONE (
    CodiceOp INT PRIMARY KEY AUTO_INCREMENT,
    NomeOp VARCHAR(50) NOT NULL,
    Durata SMALLINT NOT NULL,
    FacciaOp TINYINT NOT NULL,
    FacciaAppoggio TINYINT NOT NULL,
    OperazioneSignificativa INT REFERENCES OPERAZIONE_SIGNIFICATIVA(CodiceOpSig) ON DELETE SET NULL ON UPDATE CASCADE,
    Parte INT NOT NULL REFERENCES PARTE(CodParte) ON DELETE NO ACTION ON UPDATE CASCADE,
    CHECK(Durata > 0)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS OPERAZIONE_MANCANTE;
CREATE TABLE OPERAZIONE_MANCANTE (
    Operazione INT REFERENCES OPERAZIONE(CodiceOp) ON DELETE CASCADE ON UPDATE CASCADE,
    UnitaPersa INT REFERENCES UNITA_PERSA(CodPersa) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(Operazione, UnitaPersa)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS OPERAZIONE_SIGNIFICATIVA;
CREATE TABLE OPERAZIONE_SIGNIFICATIVA (
    CodiceOpSig INT PRIMARY KEY AUTO_INCREMENT,
    NomeOpSig VARCHAR(50) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS ORDINE;
CREATE TABLE ORDINE (
    CodOrdine INT PRIMARY KEY AUTO_INCREMENT,
    Orario TIMESTAMP NOT NULL,
    Stato VARCHAR(16) DEFAULT('In processazione') NOT NULL,
    Account VARCHAR(30) REFERENCES ACCOUNT(Username) ON DELETE SET NULL ON UPDATE CASCADE,
    Via VARCHAR(50) NOT NULL,
    NumCivico VARCHAR(4) NOT NULL,
    Citta VARCHAR(50) NOT NULL,
    FOREIGN KEY(Via, NumCivico, Citta) REFERENCES INDIRIZZO(Via, NumCivico, Citta)ON DELETE NO ACTION ON UPDATE CASCADE,
    CHECK(Stato='In processazione' OR Stato='In preparazione' OR Stato='Spedito' OR Stato='Evaso' OR Stato='Pendente')
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS ORDINE_PARTI;
CREATE TABLE ORDINE_PARTI (
    CodOrdParti INT PRIMARY KEY AUTO_INCREMENT,
    Data DATE NOT NULL DEFAULT(CURRENT_DATE),
    DataConsPrev DATE NOT NULL,
    DataConsEff DATE DEFAULT(NULL),
    Ticket INT NOT NULL REFERENCES INTERVENTO_PREVENTIVO(Ticket) ON DELETE NO ACTION ON UPDATE CASCADE,
    CHECK(Data < DataConsPrev)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS PRODOTTO_PENDENTE;
CREATE TABLE PRODOTTO_PENDENTE (
    ModelloProd VARCHAR(10),
    MarcaProd VARCHAR(20),
    Ordine INT REFERENCES ORDINE(CodOrdine) ON DELETE CASCADE ON UPDATE CASCADE,
    Numero TINYINT,
    DataDisponibile DATE DEFAULT(NULL),
    PRIMARY KEY(ModelloProd, MarcaProd, Ordine, Numero),
    FOREIGN KEY(ModelloProd,MarcaProd) REFERENCES PRODOTTO(Modello,Marca) ON DELETE NO ACTION ON UPDATE CASCADE,
    CHECK(Numero > 0)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS PARTE;
CREATE TABLE PARTE (
    CodParte INT PRIMARY KEY AUTO_INCREMENT,
    NomeParte VARCHAR(30) NOT NULL,
    Prezzo NUMERIC(6,2) NOT NULL,
    Peso INTEGER NOT NULL,                /*Peso in grammi*/
    CoeffSvalutazione NUMERIC(3,2) NOT NULL,       /*Valore compreso tra 0 e 1*/
    PercentualeSost TINYINT DEFAULT(70) NOT NULL,
    CHECK(Prezzo > 0 AND Peso > 0 AND CoeffSvalutazione BETWEEN 0 AND 1 AND PercentualeSost BETWEEN 0 AND 100)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS PERTINENZA;
CREATE TABLE PERTINENZA (
    Operazione INT REFERENCES OPERAZIONE(CodiceOp) ON DELETE CASCADE ON UPDATE CASCADE,
    ModelloProd VARCHAR(10),
    MarcaProd VARCHAR(20),
    PRIMARY KEY(Operazione, ModelloProd, MarcaProd),
    FOREIGN KEY(ModelloProd,MarcaProd) REFERENCES PRODOTTO(Modello,Marca) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS PROBLEMA;
CREATE TABLE PROBLEMA (
    Casistica INT REFERENCES CASISTICA(CodCasistica) ON DELETE CASCADE ON UPDATE CASCADE,
    ModelloProd VARCHAR(10),
    MarcaProd VARCHAR(20),
    FOREIGN KEY(ModelloProd,MarcaProd) REFERENCES PRODOTTO(Modello,Marca) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(Casistica, ModelloProd, MarcaProd)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS PROCEDURA;
CREATE TABLE PROCEDURA (
    CodiceErrore INT REFERENCES CODICE_ERRORE(CodErrore) ON DELETE CASCADE ON UPDATE CASCADE,
    Rimedio INT REFERENCES RIMEDIO(CodRimedio) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(CodiceErrore, Rimedio)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS RECENSIONE;
CREATE TABLE RECENSIONE (
    CodRecensione INT PRIMARY KEY AUTO_INCREMENT,
    ModelloProd VARCHAR(10) NOT NULL,
    MarcaProd VARCHAR(20) NOT NULL,
    Account VARCHAR(30) REFERENCES ACCOUNT(Username) ON DELETE SET NULL ON UPDATE CASCADE,
    Affidabilita TINYINT NOT NULL,
    EsperienzaUso TINYINT NOT NULL,
    Performance TINYINT NOT NULL,
    Aspetto TINYINT NOT NULL,
    RapportoQualitaPrezzo TINYINT NOT NULL,
    Descrizione VARCHAR(2000),
    FOREIGN KEY(ModelloProd,MarcaProd) REFERENCES PRODOTTO(Modello,Marca) ON DELETE CASCADE ON UPDATE CASCADE,
    CHECK(Affidabilita BETWEEN 1 AND 5 AND EsperienzaUso BETWEEN 1 AND 5 AND Performance BETWEEN 1 AND 5 AND Aspetto BETWEEN 1 AND 5 AND RapportoQualitaPrezzo BETWEEN 1 AND 5)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS RICAMBIO;
CREATE TABLE RICAMBIO (
    OrdineParti INT REFERENCES ORDINE_PARTI(CodOrdineParti) ON DELETE CASCADE ON UPDATE CASCADE,
    Parte INT REFERENCES PARTE(CodParte) ON DELETE CASCADE ON UPDATE CASCADE,
    Numero TINYINT NOT NULL,
    PRIMARY KEY(OrdineParti, Parte),
    CHECK(Numero > 0)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS RICEVUTA;
CREATE TABLE RICEVUTA (
    CodRicevuta INT PRIMARY KEY AUTO_INCREMENT,
    Costo NUMERIC(6,2) NOT NULL,
    VociDiCosto VARCHAR(300) NOT NULL,
    ModPagamento VARCHAR(16) NOT NULL,
    Ticket INT REFERENCES INTERVENTO_RIPARATIVO(Ticket) ON DELETE NO ACTION ON UPDATE CASCADE,
    CHECK(Costo > 0 AND (ModPagamento='Contanti' OR ModPagamento='Carta di debito' OR ModPagamento='Carta di credito' OR ModPagamento='Assegno' OR ModPagamento='Bonifico'))
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS RICHIESTA_RESO;
CREATE TABLE RICHIESTA_RESO (
    CodReso INT PRIMARY KEY AUTO_INCREMENT,
    Accettata BOOLEAN DEFAULT(NULL),
    Data DATE DEFAULT(CURRENT_DATE) NOT NULL,
    Unita INT NOT NULL REFERENCES UNITA(CodSer) ON DELETE NO ACTION ON UPDATE CASCADE,
    Motivazione INT NOT NULL REFERENCES MOTIVAZIONE(CodMotivazione) ON DELETE NO ACTION ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS RIMEDIO;
CREATE TABLE RIMEDIO (
    CodRimedio INT PRIMARY KEY AUTO_INCREMENT,
    Descrizione VARCHAR(500) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS SEQUENZA;
CREATE TABLE SEQUENZA (
    CodSequenza INT PRIMARY KEY AUTO_INCREMENT,
    Descrizione VARCHAR(200) NOT NULL,
    ModelloProd VARCHAR(10) NOT NULL,
    MarcaProd VARCHAR(20) NOT NULL,
    FOREIGN KEY(ModelloProd,MarcaProd) REFERENCES PRODOTTO(Modello,Marca) ON DELETE NO ACTION ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS SOSTITUZIONE;
CREATE TABLE SOSTITUZIONE (
    Parte INT REFERENCES PARTE(CodParte) ON DELETE NO ACTION ON UPDATE CASCADE,
    UnitaRicondizionata INT REFERENCES UNITA_RICONDIZIONATA(Unita) ON DELETE CASCADE ON UPDATE CASCADE,
    Numero TINYINT NOT NULL DEFAULT(1),
    PRIMARY KEY(Parte, UnitaRicondizionata)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS SPEDIZIONE;
CREATE TABLE SPEDIZIONE (
    CodSpedizione INT PRIMARY KEY AUTO_INCREMENT,
    DataPartenza DATE DEFAULT(CURRENT_DATE) NOT NULL,
    DataArrivo DATE DEFAULT(NULL),
    DataPrevista DATE NOT NULL,
    Stato VARCHAR(11) DEFAULT('Spedita') NOT NULL,
    Ordine INT NOT NULL REFERENCES ORDINE(CodOrdine) ON DELETE NO ACTION ON UPDATE CASCADE,
    CHECK(Stato='Spedita' OR Stato='In transito' OR Stato='In consegna' OR Stato='Consegnata')
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS STORICO_STOCCAGGIO;
CREATE TABLE STORICO_STOCCAGGIO (
    Lotto INT REFERENCES LOTTO(CodiceLotto) ON DELETE NO ACTION ON UPDATE CASCADE,
    Magazzino INT REFERENCES MAGAZZINO(CodMagazzino) ON DELETE NO ACTION ON UPDATE CASCADE,
    Area VARCHAR(3) NOT NULL,                      /*A11,B12,C35*/
    DataInizioStock DATE NOT NULL,
    DataFineStock DATE DEFAULT(NULL),
    PRIMARY KEY(Lotto, Magazzino)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS STRUMENTO;
CREATE TABLE STRUMENTO (
    Operazione INT REFERENCES OPERAZIONE(CodiceOp) ON DELETE CASCADE ON UPDATE CASCADE,
    Utensile VARCHAR(30) REFERENCES UTENSILE(NomeUtensile) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(Operazione, Utensile)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS STRUTTURA;
CREATE TABLE STRUTTURA (
    Parte INT REFERENCES PARTE(CodParte) ON DELETE NO ACTION ON UPDATE CASCADE,
    ModelloProd VARCHAR(10),
    MarcaProd VARCHAR(20),
    Numero TINYINT NOT NULL DEFAULT(1),
    PRIMARY KEY(ModelloProd, MarcaProd, Parte),
    FOREIGN KEY(ModelloProd,MarcaProd) REFERENCES PRODOTTO(Modello,Marca) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS TECNICO;
CREATE TABLE TECNICO (
    Matricola INT PRIMARY KEY AUTO_INCREMENT,
    AreaGeografica INT NOT NULL REFERENCES AREA_GEOGRAFICA(CodArea) ON DELETE SET NULL ON UPDATE CASCADE,
    CostoManodopera NUMERIC(4,2) NOT NULL,
    DataNascita DATE NOT NULL,
    CHECK(CostoManodopera > 15)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS TEST;
CREATE TABLE TEST (
    CodiceTest INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(30) NOT NULL,
    Ordine TINYINT NOT NULL,
    TestPadre INT REFERENCES TEST(CodiceTest) ON DELETE CASCADE ON UPDATE CASCADE,
    ModelloProd VARCHAR(10),
    MarcaProd VARCHAR(20),
    FOREIGN KEY(ModelloProd,MarcaProd) REFERENCES PRODOTTO(Modello,Marca) ON DELETE CASCADE ON UPDATE CASCADE,
    CHECK(Ordine > 0)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS TRACKING;
CREATE TABLE TRACKING (
    Spedizione INT REFERENCES SPEDIZIONE(CodSpedizione) ON DELETE CASCADE ON UPDATE CASCADE,
    Hub INT REFERENCES HUB(CodiceHub) ON DELETE CASCADE ON UPDATE CASCADE,
    DataTransito TIMESTAMP DEFAULT(CURRENT_TIMESTAMP) NOT NULL,
    PRIMARY KEY(Spedizione, Hub)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS UNITA;
CREATE TABLE UNITA (
    CodSer INT PRIMARY KEY AUTO_INCREMENT,
    DataProduzione DATE DEFAULT(CURRENT_DATE) NOT NULL,
    DataSpedizione DATE DEFAULT(NULL),
    ModelloProd VARCHAR(10) NOT NULL,
    MarcaProd VARCHAR(20) NOT NULL,
    Lotto INT NOT NULL REFERENCES LOTTO(CodiceLotto) ON DELETE NO ACTION ON UPDATE CASCADE,
    Spedizione INT REFERENCES SPEDIZIONE(CodSpedizione) ON DELETE NO ACTION ON UPDATE CASCADE,
    Ordine INT REFERENCES ORDINE(CodOrdine) ON DELETE NO ACTION ON UPDATE CASCADE,
    FOREIGN KEY(ModelloProd,MarcaProd) REFERENCES PRODOTTO(Modello,Marca) ON DELETE NO ACTION ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS UNITA_PERSA;
CREATE TABLE UNITA_PERSA (
    CodPersa INT PRIMARY KEY AUTO_INCREMENT,
    Orario TIMESTAMP NOT NULL,
    NumStazione SMALLINT NOT NULL,
    Linea INT NOT NULL,
    Lotto INT NOT NULL REFERENCES LOTTO(CodiceLotto) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(NumStazione, Linea) REFERENCES STAZIONE(NumStazione, Linea) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS UNITA_RESA;
CREATE TABLE UNITA_RESA (
    Unita INT PRIMARY KEY AUTO_INCREMENT REFERENCES UNITA(CodSer) ON DELETE CASCADE ON UPDATE CASCADE,
    DataStoccaggio DATE NOT NULL,
    Lotto INT NOT NULL REFERENCES LOTTO(CodiceLotto) ON DELETE NO ACTION ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS UNITA_RICONDIZIONATA;
CREATE TABLE UNITA_RICONDIZIONATA (
    Unita INT PRIMARY KEY AUTO_INCREMENT REFERENCES UNITA(CodSer) ON DELETE CASCADE ON UPDATE CASCADE,
    Categoria CHAR,
    Prezzo NUMERIC(8,2) NOT NULL,
    CHECK(Prezzo > 0 AND (Categoria = 'A' OR Categoria = 'B' OR Categoria IS NULL))
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS UTENSILE;
CREATE TABLE UTENSILE (
    NomeUtensile VARCHAR(30) PRIMARY KEY
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS UTENTE;
CREATE TABLE UTENTE (
    CodFiscale CHAR(16) PRIMARY KEY,
    Nome VARCHAR(20) NOT NULL,
    Cognome VARCHAR(30) NOT NULL,
    DataNascita DATE NOT NULL,
    DataIscrizione DATE DEFAULT(CURRENT_DATE) NOT NULL,
    NumTel NUMERIC(10) NOT NULL,
    Via VARCHAR(50) NOT NULL,
    NumCivico VARCHAR(4) NOT NULL,
    Citta VARCHAR(50) NOT NULL,
    Documento VARCHAR(10) NOT NULL REFERENCES DOCUMENTO(NumDoc) ON DELETE NO ACTION ON UPDATE CASCADE,
    FOREIGN KEY(Via, NumCivico, Citta) REFERENCES INDIRIZZO(Via, NumCivico, Citta) ON DELETE NO ACTION ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS VINCOLO;
CREATE TABLE VINCOLO (
    OpPrecedente INT REFERENCES OPERAZIONE(CodiceOp) ON DELETE CASCADE ON UPDATE CASCADE,
    OpSuccessiva INT REFERENCES OPERAZIONE(CodiceOp) ON DELETE CASCADE ON UPDATE CASCADE,
    Peso SMALLINT,
    PRIMARY KEY(OpPrecedente, OpSuccessiva),
    CHECK(Peso > 0)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;